### ISSUE TITLE
DB Structure DDL or Dump

### ISSUE THREAD

**Issue by muratso** [ontio/ontology-explorer#316]
Hey @leej1012 do you happen to have a full dump of the synhandler/explorer DB? I feel like there are a few things missing from the migrations folder.

I tried to create a database from scratch and sync the whole thing from scratch... even after running the migrations I ended up facing some issues related to the incorrect size of some fields. If you don't have a dump to provide, would be possible to send the DDL of all the tables?

On our side this endpoint > https://explorer.ont.io/v2/addresses/AQLEQomhAKpZjQENQEvjd9tsYPNFBxmeqj/transactions?page_size=20&page_number=1
is showing the wrong amount.  As you can see in this endpoint, the amount is `"amount": "0.007433182",`. On our servers, it is showing `"amount": "7433182",`. I think this might be related to some field with the wrong type.

Sorry for asking this, and thanks for being so responsive.

**Comment by muratso** [comment]
Some additional info... this happened after our nodes get stuck at a specific height and we were forced to upgrade our nodes to `v2.3.5`. After that our explorer/synhandler stopped working and we tried to make it work with the latest commit on  `version2.1.0`

**Comment by leej1012** [comment]
The latest DDL of all the tables is in 'back-end-projects/Explorer/src/main/resources/db/migration/'. You can use flyway to create table. 

And the wrong amount is caused by the commit '19d673d9e8ae817fe7a0d90092a24a22c3c4705a' of '[back-end-projects/OntSynHandler]' and the commit 'd269253cdf289936622283fd595b5fb99b53e9a6' of '[back-end-projects/Explorer]'.

Before this two commits, ONG transfer amount was written into DB with decimals (OntSynHandler) and divided by decimals when query transaction (Explorer). But now ONG is compatible both decimals transfer (decimals 9 and decimals 18), so the amount is divided by decimals when written into DB and show amount directly when query transaction.

**Comment by muratso** [comment]
> You can use flyway to create table.

This is exactly what I tried last time when I was planning to have it synced from scratch. I'll drop/recreate my db and give it a try again. Thanks!

**Comment by muratso** [comment]
Thank you again @leej1012 . Tried to recreate the database and it seems to be working now. I think the error I was getting on my first try was fixed by this commit https://github.com/ontio/ontology-explorer/commit/d93cfc0528fdcef523272121cd236eb88d012bbb :). Closing this issue as well. Thank you so much for your help on this.
